spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventra_inventory
    username: postgres
    password: Sulli@123
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: InventoryHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: update   # dev only
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
